#!/usr/bin/env bash

# School of Engineering
# Computer Engineering
# Software Engineering (International program)
# All class year

# teach_day: 1 is Sunday

curl 'https://regis.reg.kmitl.ac.th/api' \
  --get \
  -d 'function=get-teach-table-show' \
  -d 'mode=by_class' \
  -d 'selected_year=2568' \
  -d 'selected_semester=2' \
  -d 'selected_faculty=01' \
  -d 'selected_department=05' \
  -d 'selected_curriculum=115' \
  -d 'selected_class_year=0' \
  -d 'search_all_faculty=false' \
  -d 'search_all_department=false' \
  -d 'search_all_curriculum=false' \
  -d 'search_all_class_year=true' \
| jq '
  .[]
  | .teachtable
  | .[]
  | .data
  | .[]
  | {
    subject_id: .subject_id,
    subject_name_en: .subject_name_en,
    subject_name_th: .subject_name_th,
    credit: .credit_str,
    section: .section,
    class_type: .lect_or_prac
      | gsub("ป"; "practice")
      | gsub("ท"; "theory"),
    teach_day: .teach_day,
    teach_time_start: .teach_time,
    teach_time_end: .teach_time2,
    extra_teach_time: .teachtime_str,
    midterm_start_date_time: .midterm_start_date_time,
    midterm_end_date_time: .midterm_end_date_time,
    final_start_date_time: .final_start_date_time,
    final_end_date_time: .final_end_date_time,
    classroom: .classroom,
    classbuilding: .classbuilding,
    building_no: .building_no,
    room_no: .room_no,
    teacher_list_th: .teacher_list_th,
    teacher_list_en: .teacher_list_en,
    remark: .remark,
    rules_th: .rules_th,
    rules_en: .rules_en,
  }
' \
| jq -s
